#!/usr/bin/env python

import os
import time

n = 120
while True:
	x = 0
	try:
		with open("timer.current","r") as f:
			x = f.read().strip()
			x = int(x)
	except:
		pass

	if x == n:
		print("timer commit")
		os.system("~/Documents/GitHub/asanas/commit")
	else:
		with open("timer.current","w") as f:
			f.write(str(x+1))
	time.sleep(1)
